Repository LibrePCB-Libraries/LibrePCB_Base.lplib, pull requests merged in 2023-09, with the labels that each got.

#58 Rework DIP packages
  pkg/1cc4d1c8-c1db-41f5-8e49-f972b26e8af1/package.lp
  pkg/1ef97aa2-4611-4b82-8d1d-8e3881f48d0a/package.lp
  pkg/2511a7ed-5597-4e8c-9981-e6e2ebcf76d5/package.lp
  pkg/2afc404a-29db-4751-9ba7-dfff6996256a/package.lp
  pkg/37bfe725-ae0a-4111-8763-5b9c74c1f5a2/package.lp
  pkg/51057fee-d408-416e-bcae-4c7704ee5a93/package.lp
  pkg/767b159c-c06e-44f0-831e-70b53965179e/.librepcb-pkg
  pkg/767b159c-c06e-44f0-831e-70b53965179e/package.lp
  pkg/a37f75b8-c5c0-4d8e-a5c4-b4fad1fa4cfc/package.lp
  pkg/b482fa44-b768-4485-b3bb-03532e85ce5f/package.lp
  pkg/b988e922-f199-445b-ad28-2c57022b1b5d/package.lp
  pkg/be5766e0-4481-4778-82e4-dd11ef1d2a20/package.lp
  pkg/bfc50292-e828-4411-9802-139ba8ca7483/package.lp
  pkg/d18cdbf6-7f61-4691-b244-c21915b3fa6a/package.lp
  pkg/d1e4b152-0fd5-4ced-9c46-691c0e1d7105/package.lp
  pkg/d879b25c-dcdc-490a-834a-4a73aa2c828c/package.lp
  pkg/de5b921e-fa7b-4a44-8424-de9a631d7fa4/package.lp
  pkg/e316abe4-5fdd-4081-a037-8e0e8e68daac/package.lp
  pkg/fd311ad7-e43e-4354-ad2e-7680e9ac3d99/package.lp
Labels: fix, ready for review

#100 Add sym/cmp for crystals with a grounded case
  cmp/2c5d2ae0-a3db-45cc-b04b-8ba114d1c9ce/.librepcb-cmp
  cmp/2c5d2ae0-a3db-45cc-b04b-8ba114d1c9ce/component.lp
  sym/2a72cc54-d2bf-4a98-a996-c645eae27b44/.librepcb-sym
  sym/2a72cc54-d2bf-4a98-a996-c645eae27b44/symbol.lp
Labels: addition, ready for review

#95 Add pkg TO-225AA (TO-126)
  pkg/a8b19673-ed93-4b92-9be6-e0a8d8914654/.librepcb-pkg
  pkg/a8b19673-ed93-4b92-9be6-e0a8d8914654/package.lp
Labels: addition, ready for review

#111 Add pkg/dev for solder jumper 2P/3P
  cmp/984bb9b3-2d2c-44a0-8cac-478778182d78/component.lp
  cmp/fa191b80-60d2-478d-a564-d677bd0fac6a/component.lp
  dev/4755190b-211e-460d-9d6c-1f2efd9868a2/.librepcb-dev
  dev/4755190b-211e-460d-9d6c-1f2efd9868a2/device.lp
  dev/477afff9-a1f8-4198-88c2-4f166a2f8108/.librepcb-dev
  dev/477afff9-a1f8-4198-88c2-4f166a2f8108/device.lp
  pkg/332ca976-74c3-404d-9888-9b716b34240b/.librepcb-pkg
  pkg/332ca976-74c3-404d-9888-9b716b34240b/package.lp
  pkg/cb971448-b280-4eaf-9aae-72b463ddbbaf/.librepcb-pkg
  pkg/cb971448-b280-4eaf-9aae-72b463ddbbaf/package.lp
Labels: addition, ready for review

#109 Add sym/cmp for HD44780 compatible displays
  cmp/6f95c738-f4b5-40a7-bbe8-b0d27b3918ee/.librepcb-cmp
  cmp/6f95c738-f4b5-40a7-bbe8-b0d27b3918ee/component.lp
  cmp/adc68cde-7111-49fc-a93b-13870c24883b/.librepcb-cmp
  cmp/adc68cde-7111-49fc-a93b-13870c24883b/component.lp
  sym/081b86b4-8fe7-4b36-8be5-e7ae75eadba8/.librepcb-sym
  sym/081b86b4-8fe7-4b36-8be5-e7ae75eadba8/symbol.lp
  sym/10c79f3e-cdc0-4045-842b-5ebf26560cc5/.librepcb-sym
  sym/10c79f3e-cdc0-4045-842b-5ebf26560cc5/symbol.lp
Labels: addition, ready for review

#113 Add sym/cmp/pkg/dev for OSHW and CE logos
  cmp/10118da4-3006-423e-99b4-076adb434065/.librepcb-cmp
  cmp/10118da4-3006-423e-99b4-076adb434065/component.lp
  cmp/fd6a7853-5719-4a03-8af3-55d30ec578dc/.librepcb-cmp
  cmp/fd6a7853-5719-4a03-8af3-55d30ec578dc/component.lp
  dev/7186a6b2-4042-451f-a698-288394ec67a7/device.lp
  dev/e0df6a4b-1064-4b65-94d5-510aa550e1eb/.librepcb-dev
  dev/e0df6a4b-1064-4b65-94d5-510aa550e1eb/device.lp
  dev/fb96b8c3-51a6-4670-b340-e8af9567abab/.librepcb-dev
  dev/fb96b8c3-51a6-4670-b340-e8af9567abab/device.lp
  pkg/8690748c-a7d6-4c9d-a4be-ad346d1b48b1/.librepcb-pkg
  pkg/8690748c-a7d6-4c9d-a4be-ad346d1b48b1/package.lp
  pkg/aaaf3401-458b-47e9-b03a-0dd4e4da972d/.librepcb-pkg
  pkg/aaaf3401-458b-47e9-b03a-0dd4e4da972d/package.lp
  pkg/b2e2ec84-841b-4d30-b031-76324d8ac8f8/package.lp
  sym/55909495-c8e4-4f52-a804-3ab0c9164fd4/.librepcb-sym
  sym/55909495-c8e4-4f52-a804-3ab0c9164fd4/symbol.lp
  sym/95ea2b87-0846-42ab-aa50-5fd230728f85/symbol.lp
  sym/cd4ebe3e-c315-4e01-b381-b22b5fdb0cda/.librepcb-sym
  sym/cd4ebe3e-c315-4e01-b381-b22b5fdb0cda/symbol.lp
Labels: addition, ready for review

#114 Add pkg for TO-92 & TO-92-WIDE
  pkg/5ee92b46-ab92-4eda-9785-99ef7a36da9f/.librepcb-pkg
  pkg/5ee92b46-ab92-4eda-9785-99ef7a36da9f/package.lp
  pkg/771d5bda-eda6-4eb8-8410-46b117e3c923/.librepcb-pkg
  pkg/771d5bda-eda6-4eb8-8410-46b117e3c923/package.lp
Labels: addition, ready for review

#110 Add sym/cmp for phototransistor NPN
  cmp/d432298e-f17c-4405-9bba-f420d6a8638f/.librepcb-cmp
  cmp/d432298e-f17c-4405-9bba-f420d6a8638f/component.lp
  sym/f7c6223f-4b2e-4a81-be8e-149e49c8b377/.librepcb-sym
  sym/f7c6223f-4b2e-4a81-be8e-149e49c8b377/symbol.lp
Labels: addition

#112 Add sym/cmp/pkg/dev for fiducial
  cmp/0a525725-d11e-4b0a-a8cb-548379fe3690/.librepcb-cmp
  cmp/0a525725-d11e-4b0a-a8cb-548379fe3690/component.lp
  dev/c675e8e3-7155-477a-8ba0-f29240635744/.librepcb-dev
  dev/c675e8e3-7155-477a-8ba0-f29240635744/device.lp
  pkg/7874663e-3f0f-445b-8646-71ec632dfcc2/.librepcb-pkg
  pkg/7874663e-3f0f-445b-8646-71ec632dfcc2/package.lp
  sym/dfad70cd-5188-4490-ab9a-a1d586b724a8/.librepcb-sym
  sym/dfad70cd-5188-4490-ab9a-a1d586b724a8/symbol.lp
Labels: addition, ready for review

#62 Add sym/cmp for resistor array/network 4..8x
  cmp/08bcb2e9-6f4b-4cc3-abee-f2f6ad966383/.librepcb-cmp
  cmp/08bcb2e9-6f4b-4cc3-abee-f2f6ad966383/component.lp
  cmp/1dff517b-3eda-478b-8b5a-47c1a510e1cc/.librepcb-cmp
  cmp/1dff517b-3eda-478b-8b5a-47c1a510e1cc/component.lp
  cmp/24f1cf85-5b96-497b-8fec-a7a33960fd95/.librepcb-cmp
  cmp/24f1cf85-5b96-497b-8fec-a7a33960fd95/component.lp
  cmp/358464dc-b8da-4dec-91b6-a671e4f06715/.librepcb-cmp
  cmp/358464dc-b8da-4dec-91b6-a671e4f06715/component.lp
  cmp/60b3e63f-a398-4913-903c-ca369c896efe/.librepcb-cmp
  cmp/60b3e63f-a398-4913-903c-ca369c896efe/component.lp
  cmp/65911b6e-615d-4d12-b0f9-fd931eb6db93/.librepcb-cmp
  cmp/65911b6e-615d-4d12-b0f9-fd931eb6db93/component.lp
  cmp/6dd4b4ba-40f7-43ea-b2f0-b3c1b6a0bc06/.librepcb-cmp
  cmp/6dd4b4ba-40f7-43ea-b2f0-b3c1b6a0bc06/component.lp
  cmp/89fa9f35-f731-48da-90e9-cee093733a47/.librepcb-cmp
  cmp/89fa9f35-f731-48da-90e9-cee093733a47/component.lp
  cmp/b17a6a4b-720a-4d3b-ab5e-318a81bbb5aa/.librepcb-cmp
  cmp/b17a6a4b-720a-4d3b-ab5e-318a81bbb5aa/component.lp
  cmp/f346d997-d09f-4e56-b9f5-f79a7227585e/.librepcb-cmp
  cmp/f346d997-d09f-4e56-b9f5-f79a7227585e/component.lp
  sym/073ed2e0-c85e-40bf-9ce7-4c65760a87d9/.librepcb-sym
  sym/073ed2e0-c85e-40bf-9ce7-4c65760a87d9/symbol.lp
  sym/07adeccc-5c7c-4c15-b922-c10cfa8dcf06/.librepcb-sym
  sym/07adeccc-5c7c-4c15-b922-c10cfa8dcf06/symbol.lp
  sym/2870ff88-3b61-4287-831a-03ffeb0db4c7/.librepcb-sym
  sym/2870ff88-3b61-4287-831a-03ffeb0db4c7/symbol.lp
  sym/34f8bde8-4300-415a-9bd9-8055eb64d51c/.librepcb-sym
  sym/34f8bde8-4300-415a-9bd9-8055eb64d51c/symbol.lp
  sym/48a864da-95e9-41d5-b57a-b41ead1df601/.librepcb-sym
  sym/48a864da-95e9-41d5-b57a-b41ead1df601/symbol.lp
  sym/4e21e978-ca73-4220-bcad-93636a27e541/.librepcb-sym
  sym/4e21e978-ca73-4220-bcad-93636a27e541/symbol.lp
  sym/7239b1a1-b57e-4b00-9577-b3e27d348dc5/.librepcb-sym
  sym/7239b1a1-b57e-4b00-9577-b3e27d348dc5/symbol.lp
  sym/81326a03-e7d7-4000-a93a-5e0bf521186a/.librepcb-sym
  sym/81326a03-e7d7-4000-a93a-5e0bf521186a/symbol.lp
  sym/8e4c4611-bd21-4043-becf-1b1a28b51fb6/.librepcb-sym
  sym/8e4c4611-bd21-4043-becf-1b1a28b51fb6/symbol.lp
  sym/92c3d646-2d97-447d-9acf-c650be50ee98/.librepcb-sym
  sym/92c3d646-2d97-447d-9acf-c650be50ee98/symbol.lp
  sym/a0653c9b-12f9-4eec-8c25-9e3f24c08245/.librepcb-sym
  sym/a0653c9b-12f9-4eec-8c25-9e3f24c08245/symbol.lp
  sym/b2bfa502-a3f0-414e-ae62-35af40c55033/.librepcb-sym
  sym/b2bfa502-a3f0-414e-ae62-35af40c55033/symbol.lp
  sym/b5abd2cf-753e-49ad-abfc-a0e577ef7006/.librepcb-sym
  sym/b5abd2cf-753e-49ad-abfc-a0e577ef7006/symbol.lp
  sym/b87c4928-4ba7-4cc2-8a12-84f982481c0b/.librepcb-sym
  sym/b87c4928-4ba7-4cc2-8a12-84f982481c0b/symbol.lp
  sym/b99657ee-7b17-4be7-84c2-4d6049aac968/.librepcb-sym
  sym/b99657ee-7b17-4be7-84c2-4d6049aac968/symbol.lp
  sym/bf60f5c2-d634-42e5-bfe0-2a484d585bb2/.librepcb-sym
  sym/bf60f5c2-d634-42e5-bfe0-2a484d585bb2/symbol.lp
  sym/d4d35fa6-5680-40e8-a514-ef984d7b23a9/.librepcb-sym
  sym/d4d35fa6-5680-40e8-a514-ef984d7b23a9/symbol.lp
  sym/d790edf7-1331-4649-aae7-a456cb5582d8/.librepcb-sym
  sym/d790edf7-1331-4649-aae7-a456cb5582d8/symbol.lp
  sym/e0804b66-7202-4e5c-a5a1-432860542869/.librepcb-sym
  sym/e0804b66-7202-4e5c-a5a1-432860542869/symbol.lp
  sym/ed043e33-dcaf-48b8-99eb-8d27987f6180/.librepcb-sym
  sym/ed043e33-dcaf-48b8-99eb-8d27987f6180/symbol.lp
Labels: addition, ready for review

#118 Rework US resistor symbol according IEEE
  sym/073ed2e0-c85e-40bf-9ce7-4c65760a87d9/symbol.lp
  sym/193ef70d-8dab-4a6c-a672-274c5bf09b68/symbol.lp
  sym/2870ff88-3b61-4287-831a-03ffeb0db4c7/symbol.lp
  sym/4746254e-b654-4fed-9c5d-9fc8cce3f5aa/symbol.lp
  sym/81326a03-e7d7-4000-a93a-5e0bf521186a/symbol.lp
  sym/a0653c9b-12f9-4eec-8c25-9e3f24c08245/symbol.lp
  sym/b5abd2cf-753e-49ad-abfc-a0e577ef7006/symbol.lp
  sym/b87c4928-4ba7-4cc2-8a12-84f982481c0b/symbol.lp
  sym/b99657ee-7b17-4be7-84c2-4d6049aac968/symbol.lp
  sym/bf60f5c2-d634-42e5-bfe0-2a484d585bb2/symbol.lp
  sym/d790edf7-1331-4649-aae7-a456cb5582d8/symbol.lp
  sym/ed043e33-dcaf-48b8-99eb-8d27987f6180/symbol.lp
Labels: fix, ready for review, enhancement

#117 Add sym/cmp/pkg/dev for a test pad
  cmp/e2659029-10eb-42f4-af23-41301bb12569/.librepcb-cmp
  cmp/e2659029-10eb-42f4-af23-41301bb12569/component.lp
  dev/1f2a25cf-bf64-4ad1-8704-bc2c02718916/.librepcb-dev
  dev/1f2a25cf-bf64-4ad1-8704-bc2c02718916/device.lp
  pkg/41647710-f771-4a76-b53d-d2486a1fb4ff/.librepcb-pkg
  pkg/41647710-f771-4a76-b53d-d2486a1fb4ff/package.lp
  sym/812b6ca6-3233-4f07-9520-20973a072e37/.librepcb-sym
  sym/812b6ca6-3233-4f07-9520-20973a072e37/symbol.lp
Labels: addition, ready for review

#116 Add generated pkg DO-204A{A,C,G,H,L,R}
  pkg/114b76dd-9167-4f74-8049-00fa97502615/.librepcb-pkg
  pkg/114b76dd-9167-4f74-8049-00fa97502615/2dcdf0dd-481a-4021-a565-9775c1f7cb3e.step
  pkg/114b76dd-9167-4f74-8049-00fa97502615/308e06c3-4f0c-4aca-b8bb-aa6f3a834680.step
  pkg/114b76dd-9167-4f74-8049-00fa97502615/4aa6bfa4-e46d-4013-8ae1-b3eecea812c2.step
  pkg/114b76dd-9167-4f74-8049-00fa97502615/62fda336-6931-4db3-b3c7-c3068a8930ac.step
  pkg/114b76dd-9167-4f74-8049-00fa97502615/701da8cc-ba7a-44b6-94bf-fec67cb12478.step
  pkg/114b76dd-9167-4f74-8049-00fa97502615/9e3f6516-c87b-4dcc-b186-6acc431409a5.step
  pkg/114b76dd-9167-4f74-8049-00fa97502615/package.lp
  pkg/1ad363ec-19d1-412b-9eca-b04acd498536/.librepcb-pkg
  pkg/1ad363ec-19d1-412b-9eca-b04acd498536/12eb8d17-1a94-4a45-aa8c-6f6584834bf8.step
  pkg/1ad363ec-19d1-412b-9eca-b04acd498536/2a628458-8bdc-4d54-ad09-5febe592398c.step
  pkg/1ad363ec-19d1-412b-9eca-b04acd498536/2b43fadb-ea79-4df2-af3f-432fabec4f25.step
  pkg/1ad363ec-19d1-412b-9eca-b04acd498536/2ffc977c-afac-4de9-9552-1f75d95e7edb.step
  pkg/1ad363ec-19d1-412b-9eca-b04acd498536/3e169dbe-55bd-4a58-a98a-6d827ff7c5a4.step
  pkg/1ad363ec-19d1-412b-9eca-b04acd498536/b9408921-617a-4228-977c-926930192a59.step
  pkg/1ad363ec-19d1-412b-9eca-b04acd498536/c4169e9a-1e5a-4934-91b0-bc99f6f07dbd.step
  pkg/1ad363ec-19d1-412b-9eca-b04acd498536/package.lp
  pkg/2634cc8c-dc89-410c-8212-dec2813d3b29/.librepcb-pkg
  pkg/2634cc8c-dc89-410c-8212-dec2813d3b29/0ae375bf-3f05-4db7-ad7c-8e36c7f7442e.step
  pkg/2634cc8c-dc89-410c-8212-dec2813d3b29/155eaf15-e0dc-4923-b6ae-c6758167e5e0.step
  pkg/2634cc8c-dc89-410c-8212-dec2813d3b29/44f8c379-0764-4e11-a670-2dbdec7b9df5.step
  pkg/2634cc8c-dc89-410c-8212-dec2813d3b29/6a5c5721-d191-41ed-8348-6b14b15a6c52.step
  pkg/2634cc8c-dc89-410c-8212-dec2813d3b29/6f728afc-c722-4166-aa36-d07f006a5332.step
  pkg/2634cc8c-dc89-410c-8212-dec2813d3b29/be415746-fdbb-40f4-a18b-9049dfe0cf7b.step
  pkg/2634cc8c-dc89-410c-8212-dec2813d3b29/package.lp
  pkg/41b05214-6707-4d58-bfcb-6336c115c816/.librepcb-pkg
  pkg/41b05214-6707-4d58-bfcb-6336c115c816/3f91842b-b58e-4e74-a6cb-b971b4b21e34.step
  pkg/41b05214-6707-4d58-bfcb-6336c115c816/467f42d0-30d8-4bc2-9da0-0aa2b60c6629.step
  pkg/41b05214-6707-4d58-bfcb-6336c115c816/5f4ac1ae-53f3-4783-a2e3-3c1d2e7852b6.step
  pkg/41b05214-6707-4d58-bfcb-6336c115c816/67053010-6fe0-4341-854f-b0c9bd7bfc91.step
  pkg/41b05214-6707-4d58-bfcb-6336c115c816/7ddd4b76-d4b1-463e-a762-05ebb47f897a.step
  pkg/41b05214-6707-4d58-bfcb-6336c115c816/9c2ab31d-db80-4772-a906-abcbc720bc8a.step
  pkg/41b05214-6707-4d58-bfcb-6336c115c816/d3c6da65-ef95-4408-80ed-2d901e540d05.step
  pkg/41b05214-6707-4d58-bfcb-6336c115c816/package.lp
  pkg/99ebcf8d-c148-4fd7-85fb-f328acd7a20f/.librepcb-pkg
  pkg/99ebcf8d-c148-4fd7-85fb-f328acd7a20f/29b130fe-e6d7-4fa6-a321-8328a2590c46.step
  pkg/99ebcf8d-c148-4fd7-85fb-f328acd7a20f/440f1121-c2e8-4cea-9f4b-6c1413694c67.step
  pkg/99ebcf8d-c148-4fd7-85fb-f328acd7a20f/5995d4be-f997-48ac-90fe-b736cad8799e.step
  pkg/99ebcf8d-c148-4fd7-85fb-f328acd7a20f/7ef0a8b9-cb56-453e-b2ff-1b9c9782ed07.step
  pkg/99ebcf8d-c148-4fd7-85fb-f328acd7a20f/96a82039-7edc-4555-9111-926e41b662ef.step
  pkg/99ebcf8d-c148-4fd7-85fb-f328acd7a20f/b13dae79-2a8a-44e1-971c-864c04ecdbf0.step
  pkg/99ebcf8d-c148-4fd7-85fb-f328acd7a20f/d5188c0a-77b9-4b61-9904-733466e82976.step
  pkg/99ebcf8d-c148-4fd7-85fb-f328acd7a20f/package.lp
  pkg/e50a3a81-465a-4b8d-8f06-f654418279c5/.librepcb-pkg
  pkg/e50a3a81-465a-4b8d-8f06-f654418279c5/42f786d7-945a-4c24-a5ed-e8fb9911a904.step
  pkg/e50a3a81-465a-4b8d-8f06-f654418279c5/66b0d775-2450-4f25-a826-3e86cd81d5cc.step
  pkg/e50a3a81-465a-4b8d-8f06-f654418279c5/835f746f-cbf9-44a0-8c43-c72e39c76399.step
  pkg/e50a3a81-465a-4b8d-8f06-f654418279c5/a6b2fc30-27c6-490c-b736-77a3fe007c07.step
  pkg/e50a3a81-465a-4b8d-8f06-f654418279c5/b0734212-1b63-4285-8d5e-db786d05e681.step
  pkg/e50a3a81-465a-4b8d-8f06-f654418279c5/c1e5d498-7731-41cb-885c-50211b38a28f.step
  pkg/e50a3a81-465a-4b8d-8f06-f654418279c5/package.lp
Labels: addition, ready for review

#119 Rework all SOT packages
  pkg/01915bf3-9987-4413-99cb-af4cd2862b73/package.lp
  pkg/0e89154b-a448-4fea-a115-169fb56c0cb9/package.lp
  pkg/5dee62bd-8765-43c3-bd15-3cdaa2af69f7/package.lp
  pkg/888c8722-8f94-400c-a41e-7d89a2da12f2/package.lp
  pkg/ecca7be5-2257-420a-9e9f-70e02368da57/package.lp
  pkg/f8289e96-50c9-4db1-8def-e85f5e652c2c/package.lp
Labels: fix, ready for review, enhancement

#122 Remove obsolete chip capacitor devices
  dev/0482b806-500c-4ebf-bad8-9bcdbe55dace/.librepcb-dev
  dev/0482b806-500c-4ebf-bad8-9bcdbe55dace/device.lp
  dev/121c06df-1bfc-46fa-bda4-9cbcda821867/.librepcb-dev
  dev/121c06df-1bfc-46fa-bda4-9cbcda821867/device.lp
  dev/46eba43f-55d2-4bab-bc17-1492e21c9741/.librepcb-dev
  dev/46eba43f-55d2-4bab-bc17-1492e21c9741/device.lp
  dev/63175133-da03-43aa-9c34-4d3b968a19fe/.librepcb-dev
  dev/63175133-da03-43aa-9c34-4d3b968a19fe/device.lp
  dev/781c74f2-a57e-4ada-96c9-1687d9ee65c0/.librepcb-dev
  dev/781c74f2-a57e-4ada-96c9-1687d9ee65c0/device.lp
  dev/86b781d0-a0a0-4660-a525-c431f199ddbe/.librepcb-dev
  dev/86b781d0-a0a0-4660-a525-c431f199ddbe/device.lp
  dev/88128b66-bb62-4964-ac98-a81e3a669940/.librepcb-dev
  dev/88128b66-bb62-4964-ac98-a81e3a669940/device.lp
  dev/8b42ed9a-addf-4c67-a11b-531dcd0c6a17/.librepcb-dev
  dev/8b42ed9a-addf-4c67-a11b-531dcd0c6a17/device.lp
  dev/c636f3fb-c815-422e-b212-c5703e6b84b7/.librepcb-dev
  dev/c636f3fb-c815-422e-b212-c5703e6b84b7/device.lp
Labels: ready for review
