Repository LibrePCB-Libraries/LibrePCB_Base.lplib, pull requests merged in 2023-10, with the labels that each got.

#123 Add sym/cmp for bridge rectifier
  cmp/5d9bb296-1b29-4121-bded-f15b9d05f23c/.librepcb-cmp
  cmp/5d9bb296-1b29-4121-bded-f15b9d05f23c/component.lp
  sym/73c16b1f-8a37-4cb7-a832-440d0be4d9f7/.librepcb-sym
  sym/73c16b1f-8a37-4cb7-a832-440d0be4d9f7/symbol.lp
  sym/ca7218a8-66ca-441e-a1fe-4b8f7fd61658/.librepcb-sym
  sym/ca7218a8-66ca-441e-a1fe-4b8f7fd61658/symbol.lp
Labels: addition, ready for review

#125 Rework pkg/dev of THT resistors
  dev/35fc5e10-cbf4-48db-91b3-1844aad77921/device.lp
  dev/a0e021c0-90ab-4415-802e-40a847f682c8/device.lp
  dev/a8b774c7-d868-4138-93c9-88c0c80598a1/device.lp
  pkg/41a60506-8fc9-4b92-8c2d-e6463e3e88d3/0fbc1ca3-f94e-4348-8b52-b89c8ca99a9c.step
  pkg/41a60506-8fc9-4b92-8c2d-e6463e3e88d3/112d375c-a964-4874-950e-88511f7fd2af.step
  pkg/41a60506-8fc9-4b92-8c2d-e6463e3e88d3/14213963-e92c-431e-b8f6-7406a90394ff.step
  pkg/41a60506-8fc9-4b92-8c2d-e6463e3e88d3/36248260-29fb-4d78-89a7-157b5e607397.step
  pkg/41a60506-8fc9-4b92-8c2d-e6463e3e88d3/3f8c5a99-3985-4e15-bc18-756eaf43e396.step
  pkg/41a60506-8fc9-4b92-8c2d-e6463e3e88d3/c4a361a6-6a90-4aad-9a49-ca9565cad035.step
  pkg/41a60506-8fc9-4b92-8c2d-e6463e3e88d3/d0693747-44dd-4c7e-aabe-2a76a09ffbc3.step
  pkg/41a60506-8fc9-4b92-8c2d-e6463e3e88d3/package.lp
  pkg/f71d0b4f-22c4-4b4f-a288-0a8490e52e90/1f62a592-1ea6-49be-9d20-5bcc472359a9.step
  pkg/f71d0b4f-22c4-4b4f-a288-0a8490e52e90/36bf1659-0eed-4666-b713-9391b383effe.step
  pkg/f71d0b4f-22c4-4b4f-a288-0a8490e52e90/62b487f0-e381-48bb-81a6-b453f22bb9fe.step
  pkg/f71d0b4f-22c4-4b4f-a288-0a8490e52e90/66e58ea8-0bac-459a-91ba-0c74ef8d98ef.step
  pkg/f71d0b4f-22c4-4b4f-a288-0a8490e52e90/9ff65b59-d48b-4afb-b3bd-6df64c297fee.step
  pkg/f71d0b4f-22c4-4b4f-a288-0a8490e52e90/e8b9150e-16a5-4445-8779-e309949ab71b.step
  pkg/f71d0b4f-22c4-4b4f-a288-0a8490e52e90/package.lp
  pkg/f9f931ea-99e7-43bb-bb52-b1facd8ffedb/086675b1-6c63-49d3-8ac2-a91cdd3af8e8.step
  pkg/f9f931ea-99e7-43bb-bb52-b1facd8ffedb/2f4a7d6f-af2b-4dc7-ad07-96b1f3c01ecb.step
  pkg/f9f931ea-99e7-43bb-bb52-b1facd8ffedb/464fe3b6-2779-47d7-a638-4992bf81c448.step
  pkg/f9f931ea-99e7-43bb-bb52-b1facd8ffedb/57bfea23-3c1a-4d61-a8b1-071a1192c1a1.step
  pkg/f9f931ea-99e7-43bb-bb52-b1facd8ffedb/6a215bc9-49d8-4575-9dac-7b880debc90d.step
  pkg/f9f931ea-99e7-43bb-bb52-b1facd8ffedb/b0c6266b-3d5a-4539-9cee-14fd2702a6a7.step
  pkg/f9f931ea-99e7-43bb-bb52-b1facd8ffedb/c3869db9-d2e8-4491-9a67-acf8a11efa35.step
  pkg/f9f931ea-99e7-43bb-bb52-b1facd8ffedb/e9114fe6-d373-4201-9e61-2cc62677604f.step
  pkg/f9f931ea-99e7-43bb-bb52-b1facd8ffedb/package.lp
Labels: ready for review, enhancement

#128 TO-92: Add 3D models & fix too small pad drills
  pkg/5ee92b46-ab92-4eda-9785-99ef7a36da9f/c62c01e1-eb56-4cc1-9eb3-d696075ca242.step
  pkg/5ee92b46-ab92-4eda-9785-99ef7a36da9f/e90cda22-4f59-4646-9ddf-5d4e95533bab.step
  pkg/5ee92b46-ab92-4eda-9785-99ef7a36da9f/fbc9800d-3b8d-4bb7-9e38-4d08084cbc1d.step
  pkg/5ee92b46-ab92-4eda-9785-99ef7a36da9f/package.lp
  pkg/771d5bda-eda6-4eb8-8410-46b117e3c923/da60a042-718c-454b-b87d-712090c81961.step
  pkg/771d5bda-eda6-4eb8-8410-46b117e3c923/package.lp
Labels: ready for review, enhancement, bug

#130 Rework SOT package names/descriptions & add 3D models
  pkg/01915bf3-9987-4413-99cb-af4cd2862b73/d8b15dc8-74ef-4399-b44c-e8c7f31edd0d.step
  pkg/01915bf3-9987-4413-99cb-af4cd2862b73/package.lp
  pkg/0e89154b-a448-4fea-a115-169fb56c0cb9/1733742c-2825-4fab-8876-2953a1e37702.step
  pkg/0e89154b-a448-4fea-a115-169fb56c0cb9/package.lp
  pkg/5dee62bd-8765-43c3-bd15-3cdaa2af69f7/bc11a112-edcc-4f7f-86fe-0bfeb1b56470.step
  pkg/5dee62bd-8765-43c3-bd15-3cdaa2af69f7/package.lp
  pkg/ecca7be5-2257-420a-9e9f-70e02368da57/3bcfb1a7-2514-4e44-8be0-b70783916d1a.step
  pkg/ecca7be5-2257-420a-9e9f-70e02368da57/package.lp
  pkg/f8289e96-50c9-4db1-8def-e85f5e652c2c/a001bb98-c971-443c-a6b0-f3c8e2f5cade.step
  pkg/f8289e96-50c9-4db1-8def-e85f5e652c2c/package.lp
Labels: ready for review, enhancement

#133 Add pkg SOT23-3P95_280X145L60X40
  pkg/6e2a0f74-1a9c-4a98-a709-6be15e35e042/.librepcb-pkg
  pkg/6e2a0f74-1a9c-4a98-a709-6be15e35e042/e32c21a7-43ec-41ae-8407-7dea0d64fec4.step
  pkg/6e2a0f74-1a9c-4a98-a709-6be15e35e042/package.lp
Labels: addition, ready for review

#131 Add sym/cmp for analog 2-axis joysticks
  cmp/292afbaf-b5a1-4801-852e-de3c87ce9a72/.librepcb-cmp
  cmp/292afbaf-b5a1-4801-852e-de3c87ce9a72/component.lp
  cmp/372b0248-b951-4a5e-842a-f8ec4e14fac0/.librepcb-cmp
  cmp/372b0248-b951-4a5e-842a-f8ec4e14fac0/component.lp
  cmpcat/588232c9-c053-4f7f-8ea2-ff4303adb7cb/.librepcb-cmpcat
  cmpcat/588232c9-c053-4f7f-8ea2-ff4303adb7cb/component_category.lp
  sym/535930c9-6dab-4797-9bca-7a89523780d5/.librepcb-sym
  sym/535930c9-6dab-4797-9bca-7a89523780d5/symbol.lp
  sym/dcb676e9-8ca1-41aa-9ca6-7961f23c8c98/.librepcb-sym
  sym/dcb676e9-8ca1-41aa-9ca6-7961f23c8c98/symbol.lp
Labels: addition, ready for review
