Repository LibrePCB-Libraries/LibrePCB_Base.lplib, pull requests merged in 2023-08, with the labels that each got.

#102 Add generated pkg DO-214{AA,AB,AC,BA}
  pkg/09222d37-5ed9-4409-aa3d-2f6d78a4fdd8/.librepcb-pkg
  pkg/09222d37-5ed9-4409-aa3d-2f6d78a4fdd8/package.lp
  pkg/11a510a7-e928-4797-8a5a-4e66bc126c7c/.librepcb-pkg
  pkg/11a510a7-e928-4797-8a5a-4e66bc126c7c/package.lp
  pkg/23044d61-28c6-42a4-aff7-c3d06ed91819/.librepcb-pkg
  pkg/23044d61-28c6-42a4-aff7-c3d06ed91819/package.lp
  pkg/4a0138a3-fa5f-4e17-8bd9-14a3d1817a98/.librepcb-pkg
  pkg/4a0138a3-fa5f-4e17-8bd9-14a3d1817a98/package.lp
  pkg/4cfa109d-bc5f-4268-8901-cc2a4349704d/.librepcb-pkg
  pkg/4cfa109d-bc5f-4268-8901-cc2a4349704d/package.lp
  pkg/6cc5ff9c-4400-44ca-8671-870b490f8ab5/.librepcb-pkg
  pkg/6cc5ff9c-4400-44ca-8671-870b490f8ab5/package.lp
  pkg/f7380b5e-1cc4-46e3-94b9-dfa7e2785056/.librepcb-pkg
  pkg/f7380b5e-1cc4-46e3-94b9-dfa7e2785056/package.lp
  pkg/fc5f3f2b-8773-4069-9961-7c14a6674568/.librepcb-pkg
  pkg/fc5f3f2b-8773-4069-9961-7c14a6674568/package.lp
Labels: addition

#105 Fix designator for transistors
  cmp/131de1ab-343f-461a-856d-1c812562d0a9/component.lp
  cmp/2e833724-610d-44d8-bd1b-e291e0002736/component.lp
Labels: bug

#107 Add/update chip capacitors from generator
  dev/0482b806-500c-4ebf-bad8-9bcdbe55dace/device.lp
  dev/06b68a18-b44e-4924-9856-d41c4e9d2506/device.lp
  dev/121c06df-1bfc-46fa-bda4-9cbcda821867/device.lp
  dev/1e884376-8400-41a9-b87f-a427fd919033/device.lp
  dev/200606ec-3693-4681-89c3-18163177926c/device.lp
  dev/22e1d311-ea1a-4abc-a0a1-34fa3877f0d4/device.lp
  dev/2704f5e1-f8c2-4565-b8bd-5a7ea9946f08/device.lp
  dev/27c53d40-ec5f-42f7-b2f7-c766f77b2ba8/device.lp
  dev/2b823e2d-8295-48d8-a153-9dcdbca5d25d/device.lp
  dev/46eba43f-55d2-4bab-bc17-1492e21c9741/device.lp
  dev/63175133-da03-43aa-9c34-4d3b968a19fe/device.lp
  dev/781c74f2-a57e-4ada-96c9-1687d9ee65c0/device.lp
  dev/86b781d0-a0a0-4660-a525-c431f199ddbe/device.lp
  dev/88128b66-bb62-4964-ac98-a81e3a669940/device.lp
  dev/8b42ed9a-addf-4c67-a11b-531dcd0c6a17/device.lp
  dev/c139e505-592b-46ba-bdf2-acb7383ea0cd/device.lp
  dev/c636f3fb-c815-422e-b212-c5703e6b84b7/device.lp
  dev/ce1ebe03-525a-406f-9039-ff651a7c87de/.librepcb-dev
  dev/ce1ebe03-525a-406f-9039-ff651a7c87de/device.lp
  dev/d0691a38-acb7-4a41-b889-99d7a2f92b10/device.lp
  dev/e80a2ba5-13dd-41f2-9cdc-f29e30a9e2ed/device.lp
  dev/fc8c6fd6-6fd0-4e61-bdcc-b20046ebfd42/.librepcb-dev
  dev/fc8c6fd6-6fd0-4e61-bdcc-b20046ebfd42/device.lp
  pkg/0a02c705-b948-4f23-b478-71543be562e1/package.lp
  pkg/11b7567a-b972-4c22-bd17-5b2b8e5c8e89/package.lp
  pkg/11fe8774-ade2-4b36-bde6-1ec36ae627df/package.lp
  pkg/15953fd4-b82f-49a4-b047-343c67995a59/package.lp
  pkg/1671d51f-c693-4254-af82-59e0c1789483/package.lp
  pkg/30f37780-2422-4a59-952d-2466d6dbb1e0/package.lp
  pkg/3e9c71fb-04bb-48c1-9aa2-06bf91d3ded1/package.lp
  pkg/4b616942-a900-4d2d-b5e1-354047aa6b4a/package.lp
  pkg/4e821afa-e63e-4d05-a98c-82ddec42143b/.librepcb-pkg
  pkg/4e821afa-e63e-4d05-a98c-82ddec42143b/package.lp
  pkg/51fbf91d-c346-4686-972e-5380cc1bedc0/package.lp
  pkg/5ad219d5-9810-4d6f-a00f-ec646045b10b/package.lp
  pkg/5c9b135f-2930-4450-8e04-954bdb1255af/package.lp
  pkg/60b715fa-bd1d-4d96-b153-2a28208f32fb/package.lp
  pkg/6e4a8f3a-84ee-4583-ac25-bff8699e5b1d/package.lp
  pkg/73309035-042c-4c0f-835b-2422ee596960/package.lp
  pkg/9dfa1c17-e5a3-4200-a68c-43fdcad611b8/package.lp
  pkg/a457f2fc-100c-4431-a441-c4cd3360db9c/package.lp
  pkg/af635769-678f-4e44-8d7a-08ece31df8a9/package.lp
  pkg/b4fff7dd-c5bf-4720-91e4-a198dbf082a5/.librepcb-pkg
  pkg/b4fff7dd-c5bf-4720-91e4-a198dbf082a5/package.lp
  pkg/e8ba475c-996c-46a3-be24-7d05594c1823/package.lp
  pkg/f716153f-40e1-415e-9cb6-086071ccde14/package.lp
Labels: fix, addition, ready for review, enhancement
