Repository LibrePCB-Libraries/LibrePCB_Base.lplib, pull requests merged in 2024-11, with the labels that each got.

#142 Add sym/cmp for antennas (standard/dipole/loop)
  cmp/2498b9bc-bfa8-40fd-91c8-19e777e05d27/.librepcb-cmp
  cmp/2498b9bc-bfa8-40fd-91c8-19e777e05d27/component.lp
  cmp/c469cf27-6fbf-4d04-9e72-b6c94ab85fa6/.librepcb-cmp
  cmp/c469cf27-6fbf-4d04-9e72-b6c94ab85fa6/component.lp
  cmp/fb6b957f-2608-48e0-8af3-ca4e5dd6c89a/.librepcb-cmp
  cmp/fb6b957f-2608-48e0-8af3-ca4e5dd6c89a/component.lp
  sym/0ef6ae07-9883-46c9-8c02-20decd8cab20/.librepcb-sym
  sym/0ef6ae07-9883-46c9-8c02-20decd8cab20/symbol.lp
  sym/1a682807-588d-4c3f-a386-9719959c8bc8/.librepcb-sym
  sym/1a682807-588d-4c3f-a386-9719959c8bc8/symbol.lp
  sym/4197951d-d719-47c2-b487-ee966ea3bc80/.librepcb-sym
  sym/4197951d-d719-47c2-b487-ee966ea3bc80/symbol.lp
Labels: addition, ready for review

#144 Add cmp for Switch SPDT 2-Position
  cmp/c5123a2e-4b57-4539-bbce-75976e968592/.librepcb-cmp
  cmp/c5123a2e-4b57-4539-bbce-75976e968592/component.lp
Labels: addition, ready for review

#145 Add cmpcat for Barrel Connectors
  cmpcat/6eb1e60c-9c2b-439c-a2c5-8df7edbeeb98/.librepcb-cmpcat
  cmpcat/6eb1e60c-9c2b-439c-a2c5-8df7edbeeb98/component_category.lp
Labels: addition, ready for review

#147 Update THT capacitors from generator, adding 3D models
  pkg/047f91ff-6dcc-4941-8426-48ffb01e009d/667d5347-ad66-4f5f-94b9-1918fd77f6d0.step
  pkg/047f91ff-6dcc-4941-8426-48ffb01e009d/package.lp
  pkg/065f98eb-43a4-4533-9076-c9a42593ea57/df0e8030-dd8e-407d-9b8c-b42b4e98bcc7.step
  pkg/065f98eb-43a4-4533-9076-c9a42593ea57/package.lp
  pkg/10994512-62cf-4260-8b6f-72a837bd5e70/78db5379-e2b4-4c90-8dfa-819f358b92ea.step
  pkg/10994512-62cf-4260-8b6f-72a837bd5e70/package.lp
  pkg/1c97bc55-ea91-4c4d-8bbe-8977f03ee654/8291a2f6-989f-4dc0-ae8d-e9ca372a9a0d.step
  pkg/1c97bc55-ea91-4c4d-8bbe-8977f03ee654/package.lp
  pkg/1ceb1564-3f56-4c42-bcf4-3981ad83b76a/0237673e-75a6-4f78-b867-437d80646b0e.step
  pkg/1ceb1564-3f56-4c42-bcf4-3981ad83b76a/package.lp
  pkg/4307560c-5055-48fd-88e6-36f8c4fa91bf/b3d51e69-663d-4bee-93da-6384fd51afa0.step
  pkg/4307560c-5055-48fd-88e6-36f8c4fa91bf/package.lp
  pkg/573a0224-9bcd-4306-b809-b589eb01af04/5df5fcbd-b6a8-4171-bf69-9934b0cfbdc0.step
  pkg/573a0224-9bcd-4306-b809-b589eb01af04/package.lp
  pkg/5bdd8800-1807-42f6-8306-bc93d701e4a7/2b58f971-49c6-48af-bebc-a4a743453a47.step
  pkg/5bdd8800-1807-42f6-8306-bc93d701e4a7/package.lp
  pkg/62d78cc0-a21e-4b5b-8c6a-647a1ecf8771/fb1f0425-4f8c-4919-b75b-2797f8567c8e.step
  pkg/62d78cc0-a21e-4b5b-8c6a-647a1ecf8771/package.lp
  pkg/638ea9cf-bce2-49ba-be7d-22c223e37bfd/af88662b-d2d0-449f-84b1-6d0dd1ef8af2.step
  pkg/638ea9cf-bce2-49ba-be7d-22c223e37bfd/package.lp
  pkg/684ebc3e-b8ca-47f8-9d84-1a4aa994341a/70926812-0898-4731-8885-bb9315f2f758.step
  pkg/684ebc3e-b8ca-47f8-9d84-1a4aa994341a/package.lp
  pkg/7a2bb0cb-c4b3-4568-93ac-383c099309a5/e99b4253-3204-4b1d-9e4b-00d46c264fc8.step
  pkg/7a2bb0cb-c4b3-4568-93ac-383c099309a5/package.lp
  pkg/7b756d32-87b4-423c-95b2-3fb1a4263a1c/56d07083-ffc1-42a0-a3e9-609179277c33.step
  pkg/7b756d32-87b4-423c-95b2-3fb1a4263a1c/package.lp
  pkg/8f12c93c-4d09-40d8-a800-f227b08aa220/48d7cc78-75ad-4f36-a4cb-1e714e253de0.step
  pkg/8f12c93c-4d09-40d8-a800-f227b08aa220/package.lp
  pkg/9e3cb807-712f-4d8a-88ec-0c7fb12b7a71/e6929347-24e8-4f39-b7d0-cdf517e5fff1.step
  pkg/9e3cb807-712f-4d8a-88ec-0c7fb12b7a71/package.lp
  pkg/a522889a-d2af-43ab-8a13-850f1742e434/9d15a709-f115-4932-aaa4-bdafec7ef9d3.step
  pkg/a522889a-d2af-43ab-8a13-850f1742e434/package.lp
  pkg/a83ebf1e-9607-4fde-a5fe-77202cacb4c4/f1d953c8-eee5-41dd-94d7-259920f9226c.step
  pkg/a83ebf1e-9607-4fde-a5fe-77202cacb4c4/package.lp
  pkg/b041f7ae-0052-4ea4-9244-577994247203/d7dbfcd8-e4e2-445b-9095-2f866d0d03a6.step
  pkg/b041f7ae-0052-4ea4-9244-577994247203/package.lp
  pkg/bbbf14d5-f359-491f-81fd-eedfeebe68a7/795384f8-a62b-48b8-b04a-85f83afd630f.step
  pkg/bbbf14d5-f359-491f-81fd-eedfeebe68a7/package.lp
  pkg/c718e83a-4b13-415c-8c96-d192831837d5/4a3bb3b8-96fe-418f-9b08-1b46de4b71da.step
  pkg/c718e83a-4b13-415c-8c96-d192831837d5/package.lp
  pkg/def6b461-05f6-4dc9-9e41-612ab34d1e59/f8ca01f3-5723-4fb9-bdf4-0e204b4fc6c1.step
  pkg/def6b461-05f6-4dc9-9e41-612ab34d1e59/package.lp
Labels: ready for review, enhancement

#148 Relay coil/solenoid symbol - change pin text alignment
  sym/7bcc74b5-a02a-4a67-bf14-3b18d76cbd09/symbol.lp
Labels: fix, ready for review
